services:
  api:
    build:
      context: ./fakeapi-backend
      dockerfile: Dockerfile
    container_name: sos-cidade-api
    ports:
      - "8000:8000"
    volumes:
      - ./fakeapi-backend/data:/app/data
    restart: unless-stopped
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sos-cidade-web
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - api
